services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../data:/data
      - ../backend/models:/app/models
      - ../backend/fraudlens.db:/app/fraudlens.db
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
